### ISSUE TITLE
FastQC wrapper sometimes get basename wrong

### ISSUE THREAD

**Issue by lparsons** [snakemake/snakemake-wrappers#14]
The logic for getting the basename (and thus the output filesnames) from FastQC doesn't quite match FastQC. For example:

Input file | FastQC Wrapper | FastQC |
| --- | --- | --- |
| sample.fastq.gz | sample_fastqc.html | sample_fastqc.html |
| sample.fastqsanger.gz | sample_fastqc.html | sample.fastqsanger_fastqc.html |

I *think* this file has the logic used: https://github.com/s-andrews/FastQC/blob/master/uk/ac/babraham/FastQC/Utilities/CasavaBasename.java

Thus something like:
```
split_ind = 2 if base.endswith(".fastq.gz") else 1
```
will work.

**Comment by johanneskoester** [comment]
Thanks! Should be fixed with PR #65.

**Comment by iromeo** [comment]
@lparsons Hi, you forgot that file could end with `*.fq.gz` so in this case old logic was ok and your fix breaks the wrapper.
